# Generated by Django 5.0.4 on 2025-01-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_doma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user1',
            old_name='verification_code',
            new_name='otp',
        ),
        migrations.AddField(
            model_name='user1',
            name='code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
